spring:
  application:
    name: nacos-dubbo-consumer
dubbo:
  registry:
    address: nacos://hadoop000:8848
  cloud:
    subscribed-services: nacos-dubbo-provider
  application:
    qos-enable: false
